language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm prune
jobs:
  include:
    - stage: test
      script: echo "Passing test stage ..."
after-success:
  - echo "Semantic Release Deployment .."
  - npm run semantic-release
branches:
  only:
  - master
