language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm prune
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
  - master
