language: node_js
node_js:
  - "stable"
before_script:
  - npm prune
jobs:
  include:
    - stage: test
      script:
        - echo "Testing Started ..."
        - echo "Linting ..." && npm run lint
        - echo "Jest ..." && npm run test
after-success:
  - echo "Semantic Release Deployment .."
  - npm run semantic-release
branches:
  only:
  - master
